name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    
    env:
      GITHUB_TOKEN: $
      
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3

      - name: Compile LaTeX document
        run: |
          docker run -i --rm -v "$(pwd)/:/work" -w /work ghcr.io/xu-cheng/texlive-full bash -c '
            shopt -s globstar
            set -e
            for d_path in ./**/*.tex; do (
              if($d_path != "glossario" && $d_path != "template")
              then
                cd "$(dirname $d_path)"
                latexmk $(basename $d_path)
              fi
            ) done'
      
      - name: commit to branch
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: documenti compilati automaticamente
          branch: out_docs
       
       
      # upload pdf compilato 
      #- uses: actions/upload-artifact@v3
      #  with:
      #    name: lettera_candidatura
      #    path: "./src/lettera_candidatura/*.pdf"
