name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3

      - name: Compile LaTeX document
        run: |
          docker run -i --rm -v "$(pwd)/:/work" -w /work ghcr.io/xu-cheng/texlive-full bash -c '
            shopt -s globstar
            set -e
            for d_path in ./**/d_*.tex; do (
              cd "$(dirname $d_path)"
              latexmk -pdflatex $(basename $d_path)
            ) done'

      - name: upload pdf
        uses: actions/checkout@v3
        with:
          repository: https://github.com/MGufo/latex-docs-action.git 
        run: |
        
      #  shopt -s globstar
        #  set -e
        #  cd ..
        #  git clone git@github.com:MGufo/latex-docs-action.git 
      # https://github.com/MGufo/latex-docs-action.git
          mv ../**/d_*.pdf ./latex-docs-action
          cd latex-docs-action
      #    git config user.name github-actions
      #    git config user.email github-actions@github.com
          git add .
          git commit -m "pdf compilati"
          git push -u origin 
