name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3

      - name: Compile LaTeX document
        run: |
          docker run -i --rm -v "$(pwd)/:/work" -w /work ghcr.io/xu-cheng/texlive-full bash -c '
            shopt -s globstar
            set -e
            for d_path in ./**/d_*.tex; do (
              cd "$(dirname $d_path)"
              latexmk -pdflatex $(basename $d_path)
            ) done'

      - name: upload pdf compilato
        run: |
          shopt -s globstar
          set -e
          mkdir out_docs
          mv ./**/d_*.pdf out_docs

          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          git add out_docs/*
          git commit -m "pdf compilati"
          git push -u https://github.com/MGufo/latex-docs-action.git master
