name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    
    env:
      GITHUB_TOKEN: $
      
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3

      - name: Compile LaTeX document
        run: |
          docker run -i --rm -v "$(pwd)/:/work" -w /work ghcr.io/xu-cheng/texlive-full bash -c '
            shopt -s globstar
            set -e
            for d_path in ./**/d_*.tex; do (
              cd "$(dirname $d_path)"
              latexmk -pdflatex $(basename $d_path)
            ) done'
            
      - uses: actions/checkout@v3
      - run: |
          git add ./**/d_*.pdf
          git commit -m "pdf autogenerati"
          git push       
       
      #- name: upload pdf compilato 
      #- uses: actions/upload-artifact@v3
      #  with:
      #    name: lettera_candidatura
      #    path: "./src/lettera_candidatura/*.pdf"
