name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    
    env:
      GITHUB_TOKEN: $
      
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3

      - name: Compile LaTeX document
        run: |
          docker run -i --rm -v "$(pwd)/:/work" -w /work ghcr.io/xu-cheng/texlive-full bash -c '
            shopt -s globstar
            set -e
            for d_path in ./**/d_*.tex; do (
              cd "$(dirname $d_path)"
              latexmk -pdflatex $(basename $d_path)
            ) done'
        
      - name: manual commit
        run: |
          git add ./*.pdf
          git commit -m "pdf compilati da workflow"
          git push origin out_docs
      
      #- name: commit to branch
      #  uses: stefanzweifel/git-auto-commit-action@v4
      #  with:
      #    commit_message: documenti compilati automaticamente
      #    repository: ${{GITHUB_WORKSPACE}}
      #    branch: out_docs
      #    status_options: --untracked-files=all
      #    file_pattern: ./.*.pdf
       
       
      # upload pdf compilato 
      #- uses: actions/upload-artifact@v3
      #  with:
      #    name: lettera_candidatura
      #    path: "./src/lettera_candidatura/*.pdf"
