name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: lettera_candidatura.tex
          working_directory: "./src/lettera_candidatura/"
          work_in_root_file_dir: true
          post_compile: "latexmk -c"
        
      # upload pdf compilato 
      - uses: actions/upload-artifact@v3
        with:
          name: lettera_candidatura
          path: "./src/lettera_candidatura/*.pdf"
